---
title: "Untitled"
author: "HD"
date: '2022-12-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
setwd("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new")

source('functions/functions_evolution_5UTR.r')
load(file="./data/all_meth_exp_signal.rdata")
load(file="./data/predict_G4_up_down.rdata")
all_meth=readRDS(file="./data/aver_meth_multiple_pos_continues2.rds")


cor_meth_dhs <- readRDS("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/data/aver_meth_dhs_multiple_pos_cor_all.rds")
all_cg=readRDS(file="./data/aver_cg_multiple_pos_continues2.rds")
all_dhs=readRDS(file="./data/aver_dhs_multiple_pos_continues2.rds")

cor_all<-readRDS(file="./data/aver_meth_multiple_pos_cor_all.rds")

cor_exp<-readRDS(file="./data/aver_exp_multiple_pos_cor_all.rds")
cor_exp_meth<-readRDS(file="./data/aver_exp_meth_multiple_pos_cor_all.rds")
cor_all_dhs<-readRDS(file="./data/aver_dhs_multiple_pos_cor_all.rds")
cor_exp_dhs <- readRDS("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/data/aver_exp_dhs_multiple_pos_cor_all.rds")

all_meth$pos1=str_split_fixed(all_meth$pos," ",2)[,1]
  temp1=str_split_fixed(all_meth$pos1,"_",2)
  neg=ifelse(as.numeric(temp1[,2])>as.numeric(temp1[,1]),1,-1)
  all_meth$position<-(as.numeric(temp1[,1])/2+as.numeric(temp1[,2])/2+50)*neg

all_cg$pos1=str_split_fixed(all_cg$pos," ",2)[,1]
  temp1=str_split_fixed(all_cg$pos1,"_",2)
  neg=ifelse(as.numeric(temp1[,2])>as.numeric(temp1[,1]),1,-1)
  all_cg$position<-(as.numeric(temp1[,1])/2+as.numeric(temp1[,2])/2+50)*neg
  

all_dhs$pos1=str_split_fixed(all_dhs$pos," ",2)[,1]
  temp1=str_split_fixed(all_dhs$pos1,"_",2)
  neg=ifelse(as.numeric(temp1[,2])>as.numeric(temp1[,1]),1,-1)
  all_dhs$position<-(as.numeric(temp1[,1])/2+as.numeric(temp1[,2])/2+50)*neg
    
  
  load(file="./data/predict_G4_up_down.rdata")

x1=all_meth[all_meth$position<=1000&all_meth$position>=-1500 & all_meth$cancer=="LUAD" ,]
x1$type_2=ifelse(x1$ensembl_gene_id %in% promoter_G4_down_pos$trans_ID[promoter_G4_down_pos[,9]<=100],"+","-")
p_preG4<-ggplot(x1,aes(x=as.factor(position),y=norm_meth,fill=type_2))+geom_boxplot()+theme_hd()+xlab("Distance of methylation regions to TSS")+ylab("DNA methylation")+theme(axis.text.x = element_text(angle = 90))+scale_fill_manual("Predicted G4s in NT strand of TSS downstream 100bp",values =   colorRampPalette(c("white" ,"#F07F16C7"))(6)[c(2,6)])+ggtitle("TCGA-LUAD")

 x1_dhs=all_dhs[all_dhs$position<=1000&all_dhs$position>=-1500 & all_dhs$cancer=="LUAD" ,]
x1_dhs$type_2=ifelse(x1_dhs$genes_main_transcript %in% promoter_G4_down_pos$trans_ID[promoter_G4_down_pos[,9]<=100],"+","-")
p_preG4_dhs<-ggplot(x1_dhs,aes(x=as.factor(position),y=signal,fill=type_2))+geom_boxplot()+theme_hd()+xlab("Distance of DHS signal regions to TSS")+ylab("DHS signal")+theme(axis.text.x = element_text(angle = 90))+scale_fill_manual("Predicted G4s in NT strand of TSS downstream 100bp",values =   colorRampPalette(c("white" ,"#F07F16C7"))(6)[c(2,6)])+ggtitle("ENCODE-Lung")
  
  
p1=ggplot(all_meth[all_meth$position<=1000&all_meth$position>=-1500 & all_meth$cancer=="LUAD" ,],aes(x=as.factor(position),y=norm_meth))+geom_boxplot()+theme_hd()+xlab("Distance to TSS")+ylab("DNA methylation")+theme(axis.text.x = element_text(angle = 90))

colnames(all_meth)<-gsub("ensembl_gene_id","ensembl_trans_id",colnames(all_meth))


all_cg$pos1=str_split_fixed(all_cg$pos," ",2)[,1]
  temp1=str_split_fixed(all_cg$pos1,"_",2)
  neg=ifelse(as.numeric(temp1[,2])>as.numeric(temp1[,1]),1,-1)
  all_cg$position<-(as.numeric(temp1[,1])/2+as.numeric(temp1[,2])/2+50)*neg
  
  all_cg_melt<-melt(all_cg,id.vars = c("pos1","pos","position","ensembl_gene_id","ensembl_trans_id"))
  all_cg_melt$value<-as.numeric(all_cg_melt$value)
p1_cg=ggplot(all_cg_melt[all_cg_melt$position<=1000&all_cg_melt$position>=-1500  ,],aes(x=as.factor(position),y=value,fill=variable))+geom_boxplot()+theme_hd()+xlab("Distance to TSS")+ylab("Frequency of G-runs")+theme(axis.text.x = element_text(angle = 90))+scale_fill_manual(name="Strand",labels=c("Non-template","Template"),values=c( "#F07F16C7","#40A4DE"))
#all_cg_melt$position<-as.factor(all_cg_melt$position)
p1_cg_sig=plotSubSigcg(all_cg_melt[all_cg_melt$position<=1000&all_cg_melt$position>=-1500  ,],"position", "value","variable","", cols1 =  c("#F07F16C7","#40A4DE"),"","Frequency of G-runs") + labs(fill = "Gene.Type")+theme(axis.text.x = element_text(angle = 90,hjust = 1), legend.position = "none")+xlab("Distance to TSS")

p1_dhs=ggplot(all_dhs[all_dhs$position<=1000&all_dhs$position>=-1500 & all_dhs$cancer=="LUAD" ,],aes(x=as.factor(position),y=signal))+geom_boxplot()+theme_hd()+xlab("Distance to TSS")+ylab("DHS signal")+theme(axis.text.x = element_text(angle = 90))+ggtitle("ENCODE-Lung")

p1_meth=ggplot(all_meth[all_meth$position<=1000&all_meth$position>=-1500 & all_meth$cancer=="LUAD" ,],aes(x=as.factor(position),y=norm_meth))+geom_boxplot()+theme_hd()+xlab("Distance to TSS")+ylab("DNA methylation")+theme(axis.text.x = element_text(angle = 90))+ggtitle("TCGA-LUAD")



p1=ggarrange(p1_cg_sig,p1_meth,p1_dhs,nrow=1,ncol=3)

pcor_meth_gg=ggplot(cor_all[cor_all$pos_gg==cor_all$pos_meth& cor_all$position_meth<=1000 &cor_all$position_meth>=-1500,],aes(x=as.factor(position_gg),y=cor))+geom_boxplot(aes(fill=type_x,alpha=I(0.1)),show.legend=F)+geom_jitter(width = 0.25,aes(col=type_x))+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+geom_hline(yintercept = c(0),linetype="dashed")+ylab("Correlation of methylation \nand G-run Frequency")+xlab("Distance of the methylated and Gruns regions to TSS")+labs(col="Strand of the G-runs")+ggtitle(" G-run  VS methylation in the same region")+scale_color_manual(values = c("#F07F16C7","#40A4DE"))

pcor_signal_gg=ggplot(cor_all_dhs[cor_all_dhs$pos_gg==cor_all_dhs$pos_meth& cor_all_dhs$position_meth<=1000 &cor_all_dhs$position_meth>=-1500,],aes(x=as.factor(position_gg),y=cor))+geom_boxplot(aes(fill=type_x,alpha=I(0.1)),show.legend=F)+geom_jitter(width = 0.25,aes(col=type_x))+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+geom_hline(yintercept = c(0),linetype="dashed")+ylab("Correlation of DHS signal \nand G-run Frequency")+xlab("Distance of the DHS signal and Gruns regions to TSS")+labs(col="Strand of the G-runs")+ggtitle(" G-run  VS DHS signal in the same region")+scale_color_manual(values = c("#F07F16C7","#40A4DE"))


pcor_signal_meth=ggplot(cor_meth_dhs[cor_meth_dhs$pos_meth==cor_meth_dhs$pos_signal & cor_meth_dhs$position_other<=1000 &cor_meth_dhs$position_other>=-1500,],aes(x=as.factor(position_other),y=cor))+geom_boxplot()+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+ylab("Correlation of methylation  and DHS signal")+xlab("Distance of the DHS regions to TSS")+ggtitle("Expression  VS DHS signal in different regions")#+geom_hline(yintercept = c(0),linetype="dashed")

p_cor_exp_dhs=ggplot(cor_exp_dhs[cor_exp_dhs$position_other<=1000 &cor_exp_dhs$position_other>=-1500,],aes(x=as.factor(position_other),y=cor))+geom_boxplot()+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+geom_hline(yintercept = c(0),linetype="dashed")+ylab("Correlation of expression and DHS signal")+xlab("Distance of the DHS regions to TSS")+ggtitle("Expression  VS DHS signal in different regions")

p_cor_exp=ggplot(cor_exp[cor_exp$position_gg<=1000 &cor_exp$position_gg>=-1500,],aes(x=as.factor(position_gg),y=cor))+geom_boxplot(aes(fill=type_x,alpha=I(0.1)),show.legend=F)+geom_jitter(width = 0.25,aes(col=type_x))+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+geom_hline(yintercept = c(0),linetype="dashed")+ylab("Correlation of expression \nand G-run Frequency")+xlab("Distance of the Gruns regions to TSS")+ggtitle("Expression  VS Gruns in different regions")+scale_color_manual(values = c("#F07F16C7","#40A4DE"))+labs(col="Strand of the G-runs")

p_cor_exp_meth=ggplot(cor_exp_meth[cor_exp_meth$position_meth<=1000 &cor_exp_meth$position_meth>=-1500,],aes(x=as.factor(position_meth),y=cor))+geom_boxplot()+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+ylab("Correlation of expression and DHS signal")+xlab("Distance of the methylation regions to TSS")+ggtitle("Expression  VS methylation in different regions")


p_cor_exp_dhs=ggplot(cor_exp_dhs[cor_exp_dhs$position_other<=1000 &cor_exp_dhs$position_other>=-1500,],aes(x=as.factor(position_other),y=cor))+geom_boxplot()+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+geom_hline(yintercept = c(0),linetype="dashed")+ylab("Correlation of expression and DHS signal")+xlab("Distance of the DHS regions to TSS")+ggtitle("Expression  VS DHS signal in different regions")
#+geom_hline(yintercept = c(0),linetype="dashed")




pcor_meth_gg100=ggplot(cor_all[cor_all$pos_gg=="0_100"& cor_all$position_meth<=1000 &cor_all$position_meth>=-1500,],aes(x=as.factor(position_meth),y=cor))+geom_boxplot(aes(fill=type_x,alpha=I(0.1)),show.legend=F)+geom_jitter(width = 0.25,aes(col=type_x))+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+geom_hline(yintercept = c(0),linetype="dashed")+ylab("Correlation of methylation and\n G-run Frequency")+xlab("Distance of the methylated regions to TSS")+labs(col="Strand of the G-runs")+ggtitle("G-run in TSS downstream 100bp  VS\n methylation in different regions")+scale_color_manual(values = c("#F07F16C7","#40A4DE"))


pcor_signal_gg100=ggplot(cor_all_dhs[cor_all_dhs$pos_gg=="0_100"& cor_all_dhs$position_meth<=1000 &cor_all_dhs$position_meth>=-1500,],aes(x=as.factor(position_meth),y=cor))+geom_boxplot(aes(fill=type_x,alpha=I(0.1)),show.legend=F)+geom_jitter(width = 0.25,aes(col=type_x))+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+geom_hline(yintercept = c(0),linetype="dashed")+ylab("Correlation of DHS signal\n and G-run Frequency")+xlab("Distance of the DHS signal regions to TSS")+labs(col="Strand of the G-runs")+ggtitle(" G-run in TSS downstream 100bp  VS\n DHS signal in different regions")+scale_color_manual(values = c("#F07F16C7","#40A4DE"))

pcor_signal_meth100=ggplot(cor_meth_dhs[cor_meth_dhs$pos_meth=="0_100" & cor_meth_dhs$position_otherdhs<=1000 &cor_meth_dhs$position_otherdhs>=-1500,],aes(x=as.factor(position_otherdhs),y=cor))+geom_boxplot()+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+ylab("Correlation of methylation\n and DHS signal")+xlab("Distance of the DHS regions to TSS")+ggtitle("Methylation in TSS downstream 100bp VS\n DHS signal in different regions")#+geom_hline(yintercept = c(0),linetype="dashed")

pcor_signal_methsignal100=ggplot(cor_meth_dhs[cor_meth_dhs$pos_signal=="0_100" & cor_meth_dhs$position_other<=1000 &cor_meth_dhs$position_other>=-1500,],aes(x=as.factor(position_other),y=cor))+geom_boxplot()+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+ylab("Correlation of methylation\n and DHS signal")+xlab("Distance of the methylation regions to TSS")+ggtitle("DHS signal in TSS downstream 100bp VS\n Methylation in different regions")#+geom_hline(yintercept = c(0),linetype="dashed")





library(raster)
library(ggplot2)




x1_lable=c("DNA methyltransferase","RNA polymerase","Transcription\ninitiation complex","transcription factor","Activator","Enhancer","Template strand","Non-template strand","Pre-mRNA","Methylated CpG","Unmethylated CpG","Repression")

img <- readPNG("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/model1.png")
g1 <- rasterGrob(img, interpolate=TRUE)
s1=qplot(1:10, 1:10, geom="blank") +
    annotation_custom(g1, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
    geom_point(aes(col=I("white")))+theme_void()
img <- readPNG("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/model2.png")
g2 <- rasterGrob(img, interpolate=TRUE)
s2=qplot(1:10, 1:10, geom="blank") +
    annotation_custom(g2, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
    geom_point(aes(col=I("white")))+theme_void()




s1=s1+annotate("text",x=8,y=c(seq(1.5,7,1.6),7.5,8.8),size=5,label=x1_lable[6:1],fontface="bold",hjust=0)
s2=s2+annotate("text",x=8,y=c(seq(2.2,9,1.55),9.6),size=5,label=x1_lable[12:7],fontface="bold",hjust=0)

p0=ggarrange(p1_meth,p1_dhs,nrow=2,ncol=1,labels=c(letters[2:3]),font.label = list(size = 18, color = "black", face = "bold"))

p1=ggarrange(p1_cg_sig,p0,p_cor_exp,nrow=1,ncol=3,labels=c(letters[1],"",letters[4]),font.label = list(size = 18, color = "black", face = "bold"))

p2=ggarrange(pcor_meth_gg,pcor_signal_gg,pcor_meth_gg100,nrow=1,ncol=3,labels=c(letters[5:7]),font.label = list(size = 18, color = "black", face = "bold"),common.legend = T,legend = "bottom")

p3=ggarrange(pcor_signal_gg100,p_preG4,p_preG4_dhs,nrow=1,ncol=3,labels=c(letters[8:10]),font.label = list(size = 18, color = "black", face = "bold"),common.legend = T,legend = "bottom")
tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/all_figure5.tiff",width = 20,height = 23,res=300,units="in",compression = "lzw")

print(ggarrange(p1,p2,p3,nrow=3,ncol=1,heights = c(1,1,1)))
dev.off()

p5=ggarrange(s1,s2,nrow=2,ncol=1,font.label = list(size = 18, color = "black", face = "bold"))

tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/all_figure6.tiff",width = 13,height = 16,res=300,units="in",compression = "lzw")

print(p5)
dev.off()


p1_dhsall=ggplot(unique(all_dhs[all_dhs$position<=1000&all_dhs$position>=-1500&all_dhs$tissue!="lung"  ,c("tissue","position","signal")]),aes(x=as.factor(position),y=signal))+geom_boxplot()+xlab("Distance to TSS")+ylab("DHS signal")+theme(axis.text.x = element_text(angle = 90))+facet_wrap(~tissue)+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90,hjust=1))

p1_methall=ggplot(all_meth[all_meth$position<=1000&all_meth$position>=-1500 &all_meth$cancer!="LUAD" ,],aes(x=as.factor(position),y=norm_meth))+geom_boxplot()+xlab("Distance to TSS")+ylab("DNA methylation")+theme(axis.text.x = element_text(angle = 90))+facet_wrap(~cancer,nrow=4,ncol=3)+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90,hjust=1))

tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/supply_all_figure6.tiff",width = 18,height = 23,res=300,units="in",compression = "lzw")
print(p1_methall)
dev.off()

tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/supply_all_figure7.tiff",width = 16,height = 23,res=300,units="in",compression = "lzw")
print(p1_dhsall)
dev.off()






temp=str_split_fixed(cor_all$pos_gg,"_",2)
cor_all$pos_gg_label=paste("Grun in ",ifelse(as.numeric(temp[,2])>as.numeric(temp[,1]),paste("TSS downstream\n",temp[,1],"-",temp[,2],"bp"),paste("TSS upstream\n",temp[,2],"-",temp[,1],"bp")),sep="")
x=unique(cor_all[,c("position_gg","pos_gg_label")])
x=x[order(x[,1]),]
cor_all$pos_gg_label<-factor(cor_all$pos_gg_label,levels = x[,2])
pcor_meth_ggall=ggplot(cor_all[ cor_all$position_meth<=1000 &cor_all$position_meth>=-1500 & cor_all$position_gg <=1000 &cor_all$position_gg>=-1500 ,],aes(x=as.factor(position_meth),y=cor))+geom_boxplot(aes(fill=type_x,alpha=I(0.1)),show.legend=F)+geom_jitter(width = 0.25,aes(col=type_x))+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+geom_hline(yintercept = c(0),linetype="dashed")+ylab("Correlation of methylation and\n G-run Frequency")+xlab("Distance of the methylated regions to TSS")+labs(col="Strand of the G-runs")+scale_color_manual(values = c("#F07F16C7","#40A4DE"))+facet_wrap(~pos_gg_label,nrow=6)

tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/supply_all_figure8.tiff",width = 20,height = 24,res=300,units="in",compression = "lzw")
print(pcor_meth_ggall)
dev.off()

temp=str_split_fixed(cor_all_dhs$pos_gg,"_",2)
cor_all_dhs$pos_gg_label=paste("Grun in ",ifelse(as.numeric(temp[,2])>as.numeric(temp[,1]),paste("TSS downstream\n",temp[,1],"-",temp[,2],"bp"),paste("TSS upstream\n",temp[,2],"-",temp[,1],"bp")),sep="")
x=unique(cor_all_dhs[,c("position_gg","pos_gg_label")])
x=x[order(x[,1]),]
cor_all_dhs$pos_gg_label<-factor(cor_all_dhs$pos_gg_label,levels = x[,2])

pcor_signal_ggall=ggplot(cor_all_dhs[ cor_all_dhs$position_meth<=1000 &cor_all_dhs$position_meth>=-1500& cor_all_dhs$position_gg <=1000 &cor_all_dhs$position_gg>=-1500,],aes(x=as.factor(position_meth),y=cor))+geom_boxplot(aes(fill=type_x,alpha=I(0.1)),show.legend=F)+geom_jitter(width = 0.25,aes(col=type_x))+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90))+geom_hline(yintercept = c(0),linetype="dashed")+ylab("Correlation of DHS signal\n and G-run Frequency")+xlab("Distance of the DHS signal regions to TSS")+labs(col="Strand of the G-runs")+scale_color_manual(values = c("#F07F16C7","#40A4DE"))+facet_wrap(~pos_gg_label,nrow=6)


tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/supply_all_figure9.tiff",width = 20,height = 24,res=300,units="in",compression = "lzw")
print(pcor_signal_ggall)
dev.off()

x1=all_meth[all_meth$position<=1000&all_meth$position>=-1500 &all_meth$cancer!="LUAD" ,]
x1$type_2=ifelse(x1$ensembl_gene_id %in% promoter_G4_down_pos$trans_ID[promoter_G4_down_pos[,9]<=100],"+","-")
p_preG4All<-ggplot(x1,aes(x=as.factor(position),y=norm_meth,fill=type_2))+geom_boxplot()+xlab("Distance of methylation regions to TSS")+ylab("DNA methylation")+theme(axis.text.x = element_text(angle = 90))+scale_fill_manual("Predicted G4s in NT strand of TSS downstream 100bp",values =   colorRampPalette(c("white" ,"#F07F16C7"))(6)[c(2,6)])+facet_wrap(~cancer,nrow=4,ncol=3)+theme_hd_minimal2()+theme(axis.text.x = element_text(angle = 90,hjust=1))



x1_dhs=unique(all_dhs[all_dhs$position<=1000&all_dhs$position>=-1500&all_dhs$tissue!="lung" ,c("signal","position","tissue","ensembl_transcript_id")])
x1_dhs$type_2=ifelse(x1_dhs$ensembl_transcript_id %in% promoter_G4_down_pos$trans_ID[promoter_G4_down_pos[,9]<=100],"+","-")
p_preG4_dhsall<-ggplot(x1_dhs,aes(x=as.factor(position),y=signal,fill=type_2))+geom_boxplot()+xlab("Distance of DHS signal regions to TSS")+ylab("DHS signal")+theme(axis.text.x = element_text(angle = 90))+scale_fill_manual("Predicted G4s in NT strand of TSS downstream 100bp",values =   colorRampPalette(c("white" ,"#F07F16C7"))(6)[c(2,6)])+facet_wrap(~tissue)+theme_hd_minimal()+theme(axis.text.x = element_text(angle = 90,hjust=1))

tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/supply_all_figure10.tiff",width = 18,height = 23,res=300,units="in",compression = "lzw")
print(p_preG4All)
dev.off()
tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/supply_all_figure11.tiff",width = 18,height = 23,res=300,units="in",compression = "lzw")
print(p_preG4_dhsall)
dev.off()






```

```{r}
all_G4=subset(all_data,G4_yes=="yes" & all_data$species!="Drosophila.melanogaster")
all_G4$species<-factor(as.character(all_G4$species),levels=c("Human","Mouse","Zebrafish"))

df_all<-as.data.frame(table(all_G4$G4_exp,all_G4$species))
p_freqG4=ggplot(df_all, aes(x = Var2, y = Freq, fill = Var1)) + 
    geom_bar(position = "fill",stat = "identity") +
    scale_y_continuous(labels = scales::percent_format())+scale_fill_manual("G4-seq",values = c("#CDCDC1","#00B2EE"))+ylab("Frequency")+theme_hd()+theme(axis.text.x = element_text(angle = 90,hjust = 1),legend.position = "bottom",axis.title.x =element_blank() )+ggtitle("DNA-G4 validated by G4-seq")
x=aggregate(df_all$Freq,list(df_all$Var2),sum)
df_all[df_all$Var1=="+",3]/x[,2]


genes_infor$G4_predict_type<-factor(genes_infor$G4_predict_type)
ps_grun<-plotSubSigParied(genes_infor, "CC_density","GG_density","G4_predict_type","",cols1=c("#40A4DE", "#F07F16C7"),"Template ","Non-template","Genes with Predicted G4s in different strands","Frequency of G-runs",cols_x="black")+ylim(0,0.18)+labs(fill = "Strand")+theme(axis.text.x =element_text(angle=15,hjust=1))

 x=list(Predicted_G4_T=genes_infor$ensembl_gene_id[genes_infor$G4_down_predict_neg=="+"],`G4-seq_validated_G4`=genes_infor$ensembl_gene_id[genes_infor$G4_down_exp=="+"])
 title_x="Overlap of G4s in TSS downstream"

p=venn.diagram(x,fill = c( "#00B2EE","#104E8B"),
               alpha = c(0.5, 0.5), cex = 1,cat.fontface = "bold",lty =2, fontfamily =3,cat.cex=1,sub.fontface="bold",margin=0.1,sub="", sub.pos = c(0.3,-0.05),filename = NULL,main=title_x,main.fontface ="bold",  main.cex = 1.2,col=NA,	ext.text = TRUE,ext.line.lwd = 2, ext.dist = -0.15,ext.length = 0.9,ext.pos = -14,rotation.degree = 185,cat.pos=c(120,240))
pVNN2<-ggarrange(p)
pVNN2

x=list(Predicted_G4_NT=genes_infor$ensembl_gene_id[genes_infor$G4_down_predict_pos=="+"],`G4-seq_validated_G4`=genes_infor$ensembl_gene_id[genes_infor$G4_down_exp=="+"])
 title_x="Overlap of G4s in TSS downstream"

p=venn.diagram(x,fill = c( "#FFC125","#104E8B"),
               alpha = c(0.5, 0.5), cex = 1,cat.fontface = "bold",lty =2, fontfamily =3,cat.cex=1,sub.fontface="bold",margin=0.1,sub="", sub.pos = c(0.3,-0.05),filename = NULL,main=title_x,main.fontface ="bold",  main.cex = 1.2,col=NA,	ext.text = TRUE,ext.line.lwd = 2, ext.dist = -0.15,ext.length = 0.9,ext.pos = -14,rotation.degree = 5)
pVNN<-ggarrange(p)
pVNN







df_all<-as.data.frame(table(genes_infor$G4_predict_type,genes_infor$Gene.Type,genes_infor$age_type2))
p_freq=ggplot(df_all, aes(x = Var3, y = Freq, fill = Var1)) + 
    geom_bar(position = "fill",stat = "identity") +
    scale_y_continuous(labels = scales::percent_format())+scale_fill_manual("Predicted G4s in different strand",values = c("#CDCDC1","#00B2EE", "#FFC125", "#8FBC8F"))+ylab("Frequency")+theme_hd_minimal2()+theme(axis.text.x = element_text(angle = 90,hjust = 1),legend.position = "bottom",axis.title.x =element_blank() )+guides(fill="none")+ggtitle("Genes with predicted G4s in different strand")

types=sort(as.character(unique(genes_infor$G4_predict_type)))
p2_exp=ggplot(data = all_data_tsg[all_data_tsg$cancer=="LUAD"& !is.na(all_data_tsg$Gene.Type),],aes(y=norm_exp,x=G4_predict_type,fill=G4_predict_type))+geom_boxplot()+geom_signif(comparisons = getComp(types),map_signif_level=TRUE,col="black", test='wilcox.test', step_increase=0.1)+ylab("Expression ")+theme_hd_minimal()+ggtitle("TCGA-LUAD normal")+theme(axis.text.x =element_blank(),legend.position = "none",axis.title.x = element_blank())+scale_fill_manual("Predicted G4s in different strand",values = c("#CDCDC1","#00B2EE", "#FFC125", "#8FBC8F"))


p3_signal=ggplot(data = genes_chromatin[genes_chromatin$cancer=="lung"& !is.na(genes_chromatin$Gene.Type),],aes(y=signal,x=G4_predict_type,fill=G4_predict_type))+geom_boxplot()+geom_signif(comparisons = getComp(types),map_signif_level=TRUE,col="black", test='wilcox.test', step_increase=0.1)+ylab("DHS signal in TSS downstream  ")+theme_hd_minimal()+ggtitle("ENCODE-Lung")+theme(axis.text.x = element_blank(),legend.position = "bottom",axis.title.x = element_blank())+scale_fill_manual("Predicted G4s in different strand",values = c("#CDCDC1","#00B2EE", "#FFC125", "#8FBC8F"))

p4_meth=ggplot(data = aver_meth_gene_strand[aver_meth_gene_strand$cancer=="LUAD",],aes(y=norm_meth,x=G4_predict_type,fill=G4_predict_type))+geom_boxplot()+geom_signif(comparisons = getComp(types),map_signif_level=TRUE,col="black", test='wilcox.test', step_increase=0.1)+ylab("Methylation in TSS downstream ")+ggtitle("TCGA-LUAD normal")+theme_hd_minimal()+theme(axis.text.x = element_blank(),legend.position = "bottom",axis.title.x = element_blank())+scale_fill_manual("Predicted G4s in different strand",values = c("#CDCDC1","#00B2EE", "#FFC125", "#8FBC8F"))+facet_wrap(~type,scales = "free_y")

pall0_strand=ggarrange(pVNN,pVNN2,nrow=2,ncol=1,labels = c(letters[2:3])  ,font.label = list(size = 18, color = "black", face = "bold"))
pall1_strand=ggarrange(ps_grun,p_freq,p2_exp,nrow=1,ncol=3,labels=c(letters[1:3]),font.label = list(size = 18, color = "black", face = "bold"))
pall2_strand=ggarrange(p3_signal,p4_meth,pall0_strand,nrow=1,ncol=3,labels=c(letters[4:6]),font.label = list(size = 18, color = "black", face = "bold"),common.legend = T,legend = "bottom")
pp<-ggarrange(pall1_strand,pall2_strand,nrow=2,ncol=1,font.label = list(size = 18, color = "black", face = "bold"))
tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/all_figure4.tiff",width = 16,height = 14,res=300,units="in",compression = "lzw")
print(pp)
dev.off()





tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/supply_all_figure6.tiff",width = 16,height = 16,res=300,units="in",compression = "lzw")
types=sort(as.character(unique(genes_infor$G4_predict_type)))
p2_exp_all=ggplot(data = all_data_tsg[all_data_tsg$cancer!="LUAD"& !is.na(all_data_tsg$Gene.Type),],aes(y=norm_exp,x=G4_predict_type,fill=G4_predict_type))+geom_boxplot()+geom_signif(comparisons = getComp(types),map_signif_level=TRUE,col="black", test='wilcox.test', step_increase=0.1)+ylab("Expression ")+theme_hd_minimal()+theme(axis.text.x =element_blank(),legend.position = "bottom",axis.title.x = element_blank())+scale_fill_manual("Predicted G4s in different strand",values = c("#CDCDC1","#00B2EE", "#FFC125", "#8FBC8F"))+facet_wrap(~cancer)
print(p2_exp_all)
dev.off()

tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/supply_all_figure5.tiff",width = 16,height = 16,res=300,units="in",compression = "lzw")
p3_signal_all=ggplot(data = genes_chromatin[genes_chromatin$cancer!="lung"& !is.na(genes_chromatin$Gene.Type),],aes(y=signal,x=G4_predict_type,fill=G4_predict_type))+geom_boxplot()+geom_signif(comparisons = getComp(types),map_signif_level=TRUE,col="black", test='wilcox.test', step_increase=0.1)+ylab("DHS signal in TSS downstream  ")+theme_hd_minimal()+theme(axis.text.x = element_blank(),legend.position = "bottom",axis.title.x = element_blank())+scale_fill_manual("Predicted G4s in different strand",values = c("#CDCDC1","#00B2EE", "#FFC125", "#8FBC8F"))+facet_wrap(~cancer)
print(p3_signal_all)
dev.off()







tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/supply_all_figure6.tiff",width = 16,height = 16,res=300,units="in",compression = "lzw")
p_meth_all<-ggplot(data = aver_meth_gene_strand[aver_meth_gene_strand$cancer!="LUAD",],aes(y=norm_meth,x=G4_predict_type,fill=G4_predict_type))+geom_boxplot()+geom_signif(comparisons = getComp(types),map_signif_level=TRUE,col="black", test='wilcox.test', step_increase=0.1)+ylab("Methylation in TSS downstream ")+theme_hd_minimal()+theme(axis.text.x = element_blank(),legend.position = "bottom",axis.title.x = element_blank())+scale_fill_manual("Predicted G4s in different strand",values = c("#CDCDC1","#00B2EE", "#FFC125", "#8FBC8F"))+facet_wrap(~cancer+type)
print(p_meth_all)
dev.off()


exp_GTEX=GTEXmedian_tpm_infor[GTEXmedian_tpm_infor$cancer%in%c("Stomach","Liver","Colon.Sigmoid","Colon.Transverse"),]
exp_melt<-reshape2::dcast(exp_GTEX[,c("cancer","genes_main_transcript","norm_exp")],genes_main_transcript~cancer)
exp_melt$min_colon<-apply(exp_melt[,c("Stomach","Colon.Sigmoid","Colon.Transverse")],1,min)
exp_melt$GTEXmax_exp_colon_liver<-apply(exp_melt[,c("Liver","min_colon")],1,max)

gene_exp=all_data_tsg[all_data_tsg$cancer %in% c("COAD","LIHC"),]
exp_melt2<-reshape2::dcast(gene_exp[,c("cancer","genes_main_transcript","norm_exp")],genes_main_transcript~cancer)
exp_melt2$tcgamax_exp_COAD_LIHC<-apply(exp_melt2[,c("COAD","LIHC")],1,max)

gene_meth<-all_meth[all_meth$cancer %in% c("COAD","LIHC") & all_meth$position<0 ,]
x_meth=aggregate(gene_meth$norm_meth,list(gene=gene_meth$ensembl_gene_id,cancer=gene_meth$cancer),mean)
meth_melt<-reshape2::dcast(x_meth,gene~cancer)
colnames(meth_melt)<-c("gene","COAD_meth","LIHC_meth")
meth_melt$tcgamin_meth_COAD_LIHC<-apply(meth_melt[,c("COAD_meth","LIHC_meth")],1,min)

select_gene<-genes_infor[genes_infor$G4_down_exp=="+" & genes_infor$G4_down_predict_pos=="+",] #& genes_infor$HK2=="HK"

exp_all<-merge(exp_melt,exp_melt2,by="genes_main_transcript")
colnames(exp_all)<-c("genes_main_transcript",paste("log_TPM1",colnames(exp_all)[-1]))
exp_meth_all<-merge(exp_all,meth_melt,by.x="genes_main_transcript",by.y="gene")
exp_meth_select<-merge(exp_meth_all,select_gene,by="genes_main_transcript")

exp_meth_select2=exp_meth_select[exp_meth_select$`log_TPM1 GTEXmax_exp_colon_liver`>8 & exp_meth_select$`log_TPM1 tcgamax_exp_COAD_LIHC`>8 & exp_meth_select$tcgamin_meth_COAD_LIHC<0.1,]


exp_meth_select2$promoter_G4_down_pos_lessthan300=ifelse(exp_meth_select2$genes_main_transcript %in% promoter_G4_down_pos$trans_ID[promoter_G4_down_pos[,9]<=300],"+","-")
genes_selected<-exp_meth_select2[,c("ensembl_gene_id",colnames(exp_meth_all),"hgnc_symbol","G4_down_predict_pos","G4_down_exp","HK2","age_type2","promoter_G4_down_pos_lessthan300","GG_density","CC_density","Gene.Type")]
write.csv(genes_selected,"./selected_Gene.csv",quote=F,row.names = F)

all_meth_gene=merge(genes_infor,all_meth,by.y="ensembl_gene_id",by.x="genes_main_transcript")

p1=ggplot(all_meth_gene[all_meth_gene$position<=1000&all_meth_gene$position>=-1500 & all_meth_gene$cancer=="LIHC" & all_meth_gene$genes_main_transcript %in% exp_meth_select2$genes_main_transcript,],aes(x=as.factor(position),y=norm_meth,label=hgnc_symbol))+geom_jitter(width=0.1,alpha=I(0.2))+theme_hd()+xlab("Distance to TSS")+ylab("DNA methylation")+theme(axis.text.x = element_text(angle = 90))+ggtitle("TCGA-LIHC")+ylim(0,0.25)+geom_text()

p2=ggplot(all_meth_gene[all_meth_gene$position<=1000&all_meth_gene$position>=-1500 & all_meth_gene$cancer=="COAD" & all_meth_gene$genes_main_transcript %in% exp_meth_select2$genes_main_transcript,],aes(x=as.factor(position),y=norm_meth,label=hgnc_symbol))+geom_jitter(width=0.1,alpha=I(0.2))+theme_hd()+xlab("Distance to TSS")+ylab("DNA methylation")+theme(axis.text.x = element_text(angle = 90))+ggtitle("TCGA-COAD")+ylim(0,0.25)+geom_text()

p3=ggplot(all_data_tsg[all_data_tsg$genes_main_transcript %in% exp_meth_select2$genes_main_transcript,],aes(x=cancer,y=norm_exp,label=hgnc_symbol))+geom_jitter(width=0.1,alpha=I(0.2))+theme_hd()+xlab("TCGA")+theme(axis.text.x = element_text(angle = 90))+ggtitle("selected genes")+geom_text()

p4=ggplot(GTEXmedian_tpm_infor[GTEXmedian_tpm_infor$genes_main_transcript %in% exp_meth_select2$genes_main_transcript,],aes(x=cancer,y=norm_exp,label=hgnc_symbol))+geom_jitter(width=0.1,alpha=I(0.2))+theme_hd()+xlab("GTEX")+theme(axis.text.x = element_text(angle = 90,hjust=1,size=7))+ggtitle("selected genes")+geom_text(size=I(3))


ggarrange(p1,p2,p3,p4,nrow=2,ncol=2)


p1=ggplot(all_data_tsg[all_data_tsg$cancer=="COAD",],aes(x=cancer,y=norm_exp))+geom_violin()+theme_hd()+geom_hline(yintercept = 8)
p2=ggplot(GTEXmedian_tpm_infor[GTEXmedian_tpm_infor$cancer=="Liver",],aes(x=cancer,y=norm_exp))+geom_violin()+theme_hd()+geom_hline(yintercept = 8)

p3=ggplot(x_meth[x_meth$cancer=="COAD",],aes(x=cancer,y=x))+geom_violin()+theme_hd()+geom_hline(yintercept = 0.1)+ylab("DNA methylation in TSS upstream")
ggarrange(p1,p2,p3,nrow=1,ncol=3)



temp_5UTR <- read.delim("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/result/human_5UTRplus.hits.max.PDS.w50.35.bed", header=FALSE, stringsAsFactors=FALSE)
colnames(temp_5UTR)<-c("chr","TSS_down_start","TSS_down_end","trans_ID","TSS_down_width","TSS_strand","ExperimentG4_chr","ExpG4_start","ExpG4_end","ExpG4_score","ExpG4_width")
colnames(promoter_G4_down_pos)<-c(colnames(promoter_G4_down_pos)[1],"TSS_down_start","TSS_down_end","TSS_down_width","TSS_strand",colnames(promoter_G4_down_pos)[6:7],"PreG4_start","PreG4_end","PreG4_width","PreG4_seq","PreG4_strand","Pre_G4_score",paste("PreG4",colnames(promoter_G4_down_pos)[14:22]))
promoter_G4_down_pos$PreG4_abs_start=0
promoter_G4_down_pos$PreG4_abs_end=0
promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="+",]$PreG4_abs_start=promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="+",]$TSS_down_start+promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="+",]$PreG4_start-1
promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="+",]$PreG4_abs_end=promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="+",]$TSS_down_start+promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="+",]$PreG4_end-1
promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="-",]$PreG4_abs_end=promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="-",]$TSS_down_end-promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="-",]$PreG4_start+1
promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="-",]$PreG4_abs_start=promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="-",]$TSS_down_end-promoter_G4_down_pos[promoter_G4_down_pos$TSS_strand=="-",]$PreG4_end+1


temp1=merge(promoter_G4_down_pos,temp_5UTR,by="trans_ID")
promoter_G4_down_pos_select<-merge(temp1,genes_selected,by.x="gene_id",by.y="ensembl_gene_id")
write.csv(promoter_G4_down_pos_select,"./selected_Gene_with_G4_infor.csv",quote=F,row.names = F)

 seq_data1<-getSeq(Hsapiens, promoter_G4_down_pos_select$seqnames,
                       start=promoter_G4_down_pos_select$PreG4_abs_start,end=promoter_G4_down_pos_select$PreG4_abs_end,strand=promoter_G4_down_pos_select$TSS_strand.x)
 
 seq_data2<-getSeq(Hsapiens, paste("chr",temp_5UTR$chr,sep=""),
                       start=temp_5UTR$ExpG4_start,end=temp_5UTR$ExpG4_end,strand=temp_5UTR$TSS_strand)
 seq_data2_df=as.data.frame(seq_data2)
 temp_5UTR$seq<-seq_data2_df$x
temp1=merge(promoter_G4_down_pos,temp_5UTR,by="trans_ID")
promoter_G4_down_pos_select<-merge(temp1,genes_selected,by.x="gene_id",by.y="ensembl_gene_id")
write.csv(promoter_G4_down_pos_select,"./selected_Gene_with_G4_infor.csv",quote=F,row.names = F)
cpg_pos<-read.table(file="./data/hm450.hg38.manifest_1000_0.bed")
HM450_cg<-read.delim("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/data/GPL18809-31921.txt", comment.char="#")
cpg_pos_df<-unique(cpg_pos[,c(1,2,3,4,6,8,9,10)])
colnames(cpg_pos_df)<-c("chr","trans_upstream1000_start","trans_upstream1000_end","genes_main_transcript","strand","prob_Start","prob_end","ID")
cpg_infor_temp<-merge(unique(genes_selected[,c("hgnc_symbol","genes_main_transcript")]),cpg_pos_df,by="genes_main_transcript")
cpg_infor<-merge(cpg_infor_temp,HM450_cg,by="ID")
write.csv(cpg_infor,"./selected_Gene_cpg_infor.csv",quote=F,row.names = F)

seq_data2<-getSeq(Hsapiens, cpg_infor$chr,
                       start=cpg_infor$probeBeg,end=cpg_infor$probeEnd,strand=cpg_infor$strand)
 seq_data2_df=as.data.frame(seq_data2)
 cpg_infor$GE<-seq_data2_df$x
 


`9606.protein.links.v11.0` <- read.csv("/media/huangdan/hardisk0/HD/my_data/HD_evolution/data/9606.protein.physical.links.full.v11.0.txt", sep="")
human_protein=as.data.frame(table(`9606.protein.links.v11.0`[,1]))
rownames(human_protein)<-substr(human_protein$Var1,6,20)

genes_infor$PPI_number_log=log10(human_protein[genes_infor$ensembl_peptide_id,2])

p1=ggplot(genes_infor,aes(x=HK2,y=PPI_number_log))  + geom_signif(comparisons = getComp(unique(as.character(genes_infor$HK2))),map_signif_level=TRUE,col="black", test='wilcox.test') +geom_boxplot(alpha=I(0.7),outlier.colour = NA,aes(fill=HK2))+ylab("Log No.of(protein protein interactions)")+theme_hd_minimal() + guides(fill="none")+scale_fill_manual(values = c("#7FFF00", "gray"))+theme(axis.title.x = element_blank(),axis.text.x = element_text(angle = 30,hjust = 1))

p2=ggplot(genes_infor[!is.na(genes_infor$age_type2),],aes(x=age_type2,y=PPI_number_log,fill=age_type2))+geom_boxplot(show.legend = FALSE)+geom_signif(comparisons=getComp(levels(genes_infor$age_type2[!is.na(genes_infor$age_type2)])), test='wilcox.test', map_signif_level=TRUE,col="black",step_increase=0.1) +theme_hd()+scale_fill_manual(values=colorRampPalette(c("white" ,"#CF8310"))(6)[2:6])+theme(axis.text.x = element_text(angle = 30,hjust = 1))+ylab("Log No.of(protein protein interactions)")+xlab("Age groups(Million years)")


```


