---
title: "Untitled"
author: "HD"
date: '2022-11-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
setwd("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new")

source('functions/functions_evolution_5UTR.r')
load(file="./data/all_meth_exp_signal.rdata")
load(file="./data/other_species_all_data.rdata")

GTEXmedian_tpm_infor<-merge(GTEXmedian_tpm,genes_infor,by.x="Gene.ID",by.y="ensembl_gene_id")
all_data_tsg$HK2=genes_infor[all_data_tsg$ensembl_gene_id,"HK2"]



p1=plotStrandCor(all_data_tsg,"norm_exp","GG_density","CC_density","age_type2",method="pearson")+ggtitle("TCGA Cohort")
  

p2=plotStrandCor(GTEXmedian_tpm_infor,"norm_exp","GG_density","CC_density","age_type2",method="pearson")+ggtitle("GTEX Cohort")
#plotStrandCor(all_data_tsg,"norm_exp","GG_density","CC_density","HK2",method="pearson")
#plotStrandCor(GTEXmedian_tpm_infor,"norm_exp","GG_density","CC_density","HK2",method="pearson")


exp2=PlotMutipleCor(GTEXmedian_tpm_infor,"CC_density","GG_density","Template","Non-template","norm_exp","Correlation of expression and frequency\nof G-runs in different strand in TSS downstream","pearson")+theme(legend.position = "bottom",legend.box ="vertical")+ylab("GTEX Cohort")+labs(fill="Strand")

exp1=PlotMutipleCor(all_data_tsg,"CC_density","GG_density","Template","Non-template","norm_exp","Correlation of expression and frequency\nof G-runs in different strand in TSS downstream","pearson")+theme(legend.position = "bottom",legend.box ="vertical")

#PlotMutipleCor(all_data_tsg[all_data_tsg$HK=="HK",],"CC_density","GG_density","Template strand","Non-template strand","norm_exp","Correlation of expression and frequency\nof G-runs in different strand in TSS downstream","pearson")+theme(legend.position = "none")



PlotMutipleCor(GTEXmedian_tpm_infor,"CC_density","GG_density","Template strand","Non-template strand","norm_exp","Correlation of expression and frequency\nof G-runs in different strand in TSS downstream","pearson")+theme(legend.position = "none")

sp1_cpd_exp1=plot_scatter_2(all_data_tsg[  all_data_tsg$cancer=="LUAD",],"CC_density","norm_exp","Frequency of G-runs\nin template strand", "Expression ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+ggtitle("TCGA-LUAD normal")+theme_hd()+ylim(0,16)


sp1_cpd_exp2=plot_scatter_2(all_data_tsg[which(all_data_tsg$cancer=="LUAD"),],"GG_density","norm_exp","Frequency of G-runs\nin non-template strand", "Expression ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+ggtitle("TCGA-LUAD normal")+theme_hd()+ylim(0,16)

ggarrange(sp1_cpd_exp1,sp1_cpd_exp2,nrow=2,ncol=1)








sp1_cpd_exp1GTEX=plot_scatter_2(GTEXmedian_tpm_infor[ GTEXmedian_tpm_infor$cancer=="Lung",],"CC_density","norm_exp","Frequency of G-runs\nin template strand", "Expression ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+ggtitle("GTEX-Lung normal")+theme_hd()+ylim(0,16)


sp1_cpd_exp2GTEX=plot_scatter_2(GTEXmedian_tpm_infor[GTEXmedian_tpm_infor$cancer=="Lung",],"GG_density","norm_exp","Frequency of G-runs\nin non-template strand", "Expression ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+ggtitle("GTEX-Lung normal")+theme_hd()+ylim(0,16)




#PlotMutipleCor(GTEXmedian_tpm_infor[GTEXmedian_tpm_infor$HK=="HK",],"CC_density","GG_density","Template strand","Non-template strand","norm_exp","Correlation of expression and frequency\nof G-runs in different strand in TSS downstream","pearson")+theme(legend.position = "none")

exp_norm_TSMI_TCGA<-aggregate(all_data_tsg$norm_exp,list(all_data_tsg$ensembl_gene_id),get_TSEI_log2)
rownames(exp_norm_TSMI_TCGA)<-exp_norm_TSMI_TCGA[,1]
genes_infor$TSMI_tissue_specificity_TCGA=exp_norm_TSMI_TCGA[genes_infor$ensembl_gene_id,2]
genes_infor$gene_tsmi_levelTCGA<-ifelse(genes_infor$TSMI_tissue_specificity_TCGA>quantile(genes_infor$TSMI_tissue_specificity_TCGA,0.75,na.rm=T),"high",ifelse(genes_infor$TSMI_tissue_specificity_TCGA<quantile(genes_infor$TSMI_tissue_specificity_TCGA,0.25,na.rm=T),"low","median"))
all_data_tsg$gene_tsmi_levelTCGA<-genes_infor[all_data_tsg$ensembl_gene_id,"gene_tsmi_levelTCGA"]

exp_norm_TSMI_gtex<-aggregate(GTEXmedian_tpm_infor$norm_exp,list(GTEXmedian_tpm_infor$Gene.ID),get_TSEI_log2)
rownames(exp_norm_TSMI_gtex)<-exp_norm_TSMI_gtex[,1]
genes_infor$TSMI_tissue_specificity_gtex=exp_norm_TSMI_gtex[genes_infor$ensembl_gene_id,2]

genes_infor$gene_tsmi_level<-ifelse(genes_infor$TSMI_tissue_specificity_gtex>quantile(genes_infor$TSMI_tissue_specificity_gtex,0.75,na.rm=T),"high",ifelse(genes_infor$TSMI_tissue_specificity_gtex<quantile(genes_infor$TSMI_tissue_specificity_gtex,0.25,na.rm=T),"low","median"))

sp1_gg_tsmiGTEX=plot_scatter_2(genes_infor,"GG_density","TSMI_tissue_specificity_gtex","Frequency of G-runs\nin non-template strand", "Tissue Specificity ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+theme_hd()+ylim(0.2,1.1)+ggtitle("GTEX Cohort")

sp1_cc_tsmiGTEX=plot_scatter_2(genes_infor,"CC_density","TSMI_tissue_specificity_gtex","Frequency of G-runs\nin template strand", "Tissue Specificity ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+theme_hd()+ylim(0.2,1.1)+ggtitle("GTEX Cohort")


sp1_gg_tsmiTCGA=plot_scatter_2(genes_infor,"GG_density","TSMI_tissue_specificity_TCGA","Frequency of G-runs\nin non-template strand", "Tissue Specificity ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+theme_hd()+ylim(0.15,1.25)+ggtitle("TCGA Cohort")

sp1_cc_tsmiTCGA=plot_scatter_2(genes_infor,"CC_density","TSMI_tissue_specificity_TCGA","Frequency of G-runs\nin template strand", "Tissue Specificity ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+theme_hd()+ylim(0.15,1.25)+ggtitle("TCGA Cohort")

pall1=ggarrange(sp1_cpd_exp2GTEX,sp1_cpd_exp1GTEX,nrow=1,ncol=2,labels=c(letters[2:3]),font.label = list(size = 18, color = "black", face = "bold"))


pall3=ggarrange(pall1,p2+ylim(0,0.37),nrow=2,ncol=1,labels=c("",letters[4]),font.label = list(size = 18, color = "black", face = "bold"))

pall4<-ggarrange(exp2,pall3,nrow=1,ncol=2,labels=c(letters[1],""),font.label = list(size = 18, color = "black", face = "bold"))

tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/all_figure2.tiff",width = 17,height = 17,res=300,units="in",compression = "lzw")
print(pall4)
dev.off()


pallS1=ggarrange(sp1_cpd_exp2,sp1_cpd_exp1,nrow=2,ncol=1,labels=c(letters[2:3]),font.label = list(size = 18, color = "black", face = "bold"))

pallS2<-ggarrange(exp1,pallS1,nrow=1,ncol=2,labels=c(letters[1],""),font.label = list(size = 18, color = "black", face = "bold"))
pallS3=ggarrange(sp1_gg_tsmiTCGA,sp1_cc_tsmiTCGA,nrow=2,ncol=1,labels=c(letters[5:6]),font.label = list(size = 18, color = "black", face = "bold"))
#pallS4=ggarrange(p1,pallS3,nrow=1,ncol=2,labels=c(letters[4],""),font.label = list(size = 18, color = "black", face = "bold"))

pallS=ggarrange(pallS2,p1+ylim(0,0.36),nrow=2,ncol=1,labels=c("",letters[4]),font.label = list(size = 18, color = "black", face = "bold"))

tiff("/media/huangdan/hardisk0/HD/my_data/HD_evolution/UTR5_new/all_figures/supply_all_figure2.tiff",width = 12,height = 14,res=300,units="in",compression = "lzw")
print(pallS)
dev.off()












spe_tsmi1=plot_scatter_density(genes_infor,"GG_density","TSMI_tissue_specificity_TCGA","Frequency of G-runs\nin non-template strand", "TSMI_tissue_specificity_TCGA ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+ggtitle("TCGA normal")+theme_hd()+ylim(0.15,1.1)

spe_tsmi2=plot_scatter_density(genes_infor,"CC_density","TSMI_tissue_specificity_TCGA","Frequency of G-runs\nin template strand", "TSMI_tissue_specificity_TCGA ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+ggtitle("TCGA normal")+theme_hd()+ylim(0.15,1.1)

ggarrange(spe_tsmi1,spe_tsmi2,nrow=1,ncol=2)
spe_tsmi1=plot_scatter_density(genes_infor[!is.na(genes_infor$age_type2),],"GG_density","TSMI_tissue_specificity_TCGA","Frequency of G-runs\nin non-template strand", "TSMI_tissue_specificity_TCGA ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+ggtitle("TCGA normal")+theme_hd()+ylim(0.15,1.1)+facet_wrap(~age_type2,nrow=1)

spe_tsmi2=plot_scatter_density(genes_infor[!is.na(genes_infor$age_type2),],"CC_density","TSMI_tissue_specificity_TCGA","Frequency of G-runs\nin template strand", "TSMI_tissue_specificity_TCGA ",0.01,15,"black")+theme(strip.background = element_blank())+ guides(colour = "none",fill = "none")+scale_color_manual(values=c("black"))+ggtitle("TCGA normal")+theme_hd()+ylim(0.15,1.1)+facet_wrap(~age_type2,nrow=1)
ggarrange(spe_tsmi1,spe_tsmi2,nrow=2,ncol=1)

max_exp<-aggregate(GTEXmedian_tpm$norm_exp,list(GTEXmedian_tpm$Gene.ID),median)


genes_infor$gene_exp_level<-ifelse(genes_infor$ensembl_gene_id %in% max_exp$Group.1[max_exp$x>quantile(max_exp$x,0.75)],"high",ifelse(genes_infor$ensembl_gene_id %in% max_exp$Group.1[max_exp$x<quantile(max_exp$x,0.25)],"low","median"))

high_gene=genes_infor$hgnc_symbol[which(genes_infor$GGccRatio>quantile(genes_infor$GGccRatio,0.75,na.rm=T))]
low_gene=genes_infor$hgnc_symbol[which(genes_infor$GGccRatio<quantile(genes_infor$GGccRatio,0.25,na.rm=T))]
other_genes=genes_infor$hgnc_symbol[!genes_infor$hgnc_symbol %in% c(high_gene,low_gene)]




gmt<-read_gmt("./data/h.all.v2022.1.Hs.symbols.gmt",tidy = T)
term2gene=as.data.frame(gmt)
term2gene$gene_set<-gsub("HALLMARK_","",term2gene$gene_set)
x=merge(term2gene,genes_infor,by.x="gene",by.y="hgnc_symbol")
x_exp=merge(x,GTEXmedian_tpm,by.x="ensembl_gene_id",by.y="Gene.ID")
temp_x=aggregate(x[,c("CC_density","GG_density")],list(gene_set=x$gene_set),mean)


x_exp=merge(x,all_data_tsg,by="ensembl_gene_id")

```


